{{- define "api.envBlock" }}
{{- $apiEnvConfig := dict -}}
{{- $_ := set $apiEnvConfig "NODE_ENV" "production" -}}
{{- $_ := set $apiEnvConfig "PORT" 80 -}}
{{- $_ := set $apiEnvConfig "CONFIG_DB_HOST" "localhost" -}}
{{- $_ := set $apiEnvConfig "CONFIG_DB_DATABASE" .Global.Values.api.database.databaseName -}}
{{- $_ := set $apiEnvConfig "CONFIG_DB_USER" .Global.Values.api.database.user -}}
{{- $_ := set $apiEnvConfig "CONFIG_APP_URL" "https://mysecondbrain.test" -}}

{{- range $k, $v := $apiEnvConfig }}
- name: {{ $k | quote }}
  value: {{ $v | quote }}
{{- end }}
{{- end }}
---
kind: Job
apiVersion: batch/v1
metadata:
  name: api-startup
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
{{ if .Values.api.serviceAccountName }}
      serviceAccountName: {{ .Values.api.serviceAccountName }}
{{ end }}
      restartPolicy: Never
      containers:
        - name: startup
          image: "{{ .Values.api.image }}"
          command:
            - yarn
            - migrate
          env:
{{- include "api.envBlock" ( dict "Global" . ) | indent 12 }}

        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.28.0
          command:
            - "/cloud_sql_proxy"
            - "-enable_iam_login"
            - "-instances={{ .Values.api.database.connectionName }}=tcp:5432"
          securityContext:
            runAsNonRoot: true