apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: mysecondbrain
spec:
  domains:
    - {{ .Values.baseHost }}
---
apiVersion: v1
kind: Service
metadata:
  name: mc-service
spec:
  selector:
    app: mc-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: managed-cert-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: my-second-brain-gke-586d27a
    networking.gke.io/managed-certificates: mysecondbrain
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: mc-service
      port:
        number: 80